# Generated by Django 3.0.6 on 2020-05-12 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200512_1049'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='resume',
            field=models.TextField(default='', max_length=500, verbose_name='Resumo'),
        ),
    ]
